spring:
  kafka:
    bootstrap-servers: yifan4:9092,yifan5:9092,yifan6:9092
    # 生产者配置
    producer:
      # 重试次数
      retries: 3
      # 16K 批量处理的最大大小 单位 byte
      batch-size: 16384
      # 32M 发送延时 当生产端积累的消息达到batch-size或接收消息linger.ms后 生产者就会将消息提交给kafka
      buffer-memory: 33554432
      # 客户端ID
      # client-id:
      # 应答级别
      # 0 把消息发送到kafka就认为发送成功
      # 1 把消息发送到kafka leader分区并且写入磁盘就认为发送成功
      # all 把消息发送到kafka leader分区 并且leader分区的副本follower对消息进行了同步就任务发送成功
      acks: 1
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 消息压缩: none lz4 gzip snappy 默认为none
      compression-type: gzip
      properties:
        partitioner:
          # 指定自定义分区器
          class: demo.kafka.producer.config.DiyPartitioner
        linger:
          # 发送延时,当生产端积累的消息达到batch-size或接收到消息linger.ms后,生产者就会将消息提交给kafka
          ms: 1000
        max:
          block:
            # KafkaProducer.send() 和partitionFor() 方法的最长阻塞时间 单位ms
            ms: 6000