server:
  port: 8080
spring:
  rabbitmq:
    host: 192.168.139.6
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 手动提交消息
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual